version: '3.8'

services:
  backend:
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
    command: npm run dev
    environment:
      NODE_ENV: development
  
  frontend:
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    command: npm run dev -- --host 0.0.0.0
    environment:
      NODE_ENV: development